title = "ArkhamCookie's Homepage"
favicon = "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAsLBjsXEcI3FQ77NBIM/zIQCv8wDQj/Lg0H/ywKBf8rCgT/KggD/yoIA/8qCAP6LQkEwRgGA00AAAAAHQ4OBDQUDv8zEg3/MRAK/y8PCf8tDAf/KwoF/ygJA/8mBwL/JQYB/yQFAf8kBAD/JAUB/yQFAP8lBQD/IAAABEIeGMQ2FQ//NRMO/zMSDP8xEAv/Lg4I/ywMBv8qCgX/KAgD/yYHAv8lBgH/JQUB/yUFAP8kBQD/JQYB/y0LBcJCHhjhOBYQ/zcVD/81FA3/E33D/wp/1f8LhtL/Co7J/wmQuP8Ilp3/CJiG/wiVd/8kEAr/JQUB/yYFAf8sCQTgRSAZ+zsZEv86FxD/OBUO/w1/4/8ZNJn/IC1+/yUva/8qOFv/Ljc7/zI/Kv8MomX/Hz4e/yYGAf8nBwL/LQoF+kkkHP8/HBX/PhoT/zwZEv8QZ+H/Ixt//zMVWv9WJFP/flBV/z8fGf8/KBD/Hpc3/yhEEv8oCAL/KAgD/y4MBf1PKCD/Qx4X/0MfF/9CHRf/GEnf/y8Wef9GE0//fipQ/6plMP9RJg//RigM/z+WGv8zRw//KwsF/ysLBv8xDgn/Uioi/0ciG/9HIRr/SCId/yIy3P89E3T/bB1e/51DSP+LRyT/ek4K/04qCv9okQr/Sk4L/y8PCf8vDgj/MxEL/1YtJf9KIxz/SiUf/y421f8rIN3/SRFw/7JDpP+aQkf/gkQf/5d1Ev9lQwr/gIwI/4+uBv9VRAv/MhEM/zcVD/9ZMCf/SyQc/00mHv9NJyr/QxzW/1gVoP9bEkD/fi47/4JIIf9eJhD/YzgP/5qWCv96dAv/NhUP/zQUDv86FxH/XDIp/0wlHv9NJR7/TSUe/08mI/96GKj/ghll/1kSJv9VFBn/bSsX/6hsE/91WhH/ORgS/zcXEf83FhD/PBoT/14zK/5NJR7/TSUf/00lH/9OJR//TiYf/64jav+iIy3/eSEd/7FGGv9rPRj/PhwV/zsZE/85GBL/OBcR/z0bFPxfNSzyTSUe/00mH/9NJR//TiYf/00lHv9NJR7/nCoy/700KP9hLR7/Qh8Y/z4cFf87GhP/OhgS/zgYEf8+HBXvZzoxxE0lHv9NJR7/TSYf/00lH/9NJR7/TCUd/0skHf9RJR7/RSAZ/0EeF/8+HBX/OxkT/zkYEv84GBH/QR4XwzghHUpMJR7/TSUd/04mH/9OJh7/TSUe/0skHf9KJBz/RyEa/0QgGf9BHhf/PRsV/zsZE/85GBL/OBgS/yUSAAMAAAAANyIdTmU5McFfNCz7XjMr/1wxKf9ZMCf/Vy0l/1IrIv9OJyD/SiUd/0ciGv9DHxjfQyAZwiMRDVAAAAAAwAMAAIABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAAwAMAAA=="
theme = "catppuccin"
search_engine = "https://duckduckgo.com/?q=%q"
footer = true

[clock]
twelve_hour = true

[[bookmarks]]
link = "https://github.com"
name = "GitHub"
shortcut = "g"

[[bookmarks]]
link = "https://arkhamcookie.com"
name = "ArkhamCookie"
